[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"

[[services]]
name = "gestion-places"

[services.healthcheck]
path = "/api/status"
interval = 30
timeout = 10
retries = 3